@startuml ObjectLayerLogic
state "ObjectLayerLogic State" as Shellguard_World_ObjectLayerLogic_State

Shellguard_World_ObjectLayerLogic_State --> Shellguard_World_ObjectLayerLogic_State : AddTree
Shellguard_World_ObjectLayerLogic_State --> Shellguard_World_ObjectLayerLogic_State : Initialize

Shellguard_World_ObjectLayerLogic_State : OnAddTree → SpawnTree
Shellguard_World_ObjectLayerLogic_State : OnInitialize → DisableTileRendering, SpawnTree

[*] --> Shellguard_World_ObjectLayerLogic_State
@enduml