@startuml TreeLayerLogic
state "TreeLayerLogic State" as Shellguard_World_TreeLayerLogic_State

Shellguard_World_TreeLayerLogic_State --> Shellguard_World_TreeLayerLogic_State : Initialize

Shellguard_World_TreeLayerLogic_State : OnInitialize → DisableTileRendering, SpawnTree
Shellguard_World_TreeLayerLogic_State : OnWorldTreePlanted() → SpawnTree

[*] --> Shellguard_World_TreeLayerLogic_State
@enduml