@startuml AppLogic
state "AppLogic State" as Shellguard_AppLogic_State {
  state "ClosingApplication" as Shellguard_AppLogic_State_ClosingApplication
  state "InGame" as Shellguard_AppLogic_State_InGame
  state "InMainMenu" as Shellguard_AppLogic_State_InMainMenu
  state "StartingGame" as Shellguard_AppLogic_State_StartingGame
}

Shellguard_AppLogic_State --> Shellguard_AppLogic_State_ClosingApplication : QuitApp
Shellguard_AppLogic_State_ClosingApplication --> Shellguard_AppLogic_State_ClosingApplication : FadeOutFinished
Shellguard_AppLogic_State_InGame --> Shellguard_AppLogic_State_ClosingApplication : QuitApp
Shellguard_AppLogic_State_InGame --> Shellguard_AppLogic_State_InMainMenu : BackToMainMenu
Shellguard_AppLogic_State_InMainMenu --> Shellguard_AppLogic_State_ClosingApplication : QuitApp
Shellguard_AppLogic_State_InMainMenu --> Shellguard_AppLogic_State_StartingGame : NewGame
Shellguard_AppLogic_State_StartingGame --> Shellguard_AppLogic_State_InGame : FadeOutFinished

Shellguard_AppLogic_State_ClosingApplication : None → FadeOut
Shellguard_AppLogic_State_ClosingApplication : OnFadeOutFinished → CloseApplication
Shellguard_AppLogic_State_InGame : None → FadeIn, HideMainMenu, SetupGame, ShowGame
Shellguard_AppLogic_State_InMainMenu : None → RemoveGame, ShowMainMenu
Shellguard_AppLogic_State_StartingGame : None → FadeOut

[*] --> Shellguard_AppLogic_State_InMainMenu
@enduml