@startuml GameLogic
state "GameLogic State" as Shellguard_Game_State_GameLogic_State {
  state "Paused" as Shellguard_Game_State_GameLogic_State_Paused
  state "Playing" as Shellguard_Game_State_GameLogic_State_Playing
}

Shellguard_Game_State_GameLogic_State --> Shellguard_Game_State_GameLogic_State : LoadRequested
Shellguard_Game_State_GameLogic_State --> Shellguard_Game_State_GameLogic_State : SaveCompleted
Shellguard_Game_State_GameLogic_State --> Shellguard_Game_State_GameLogic_State : SaveRequested
Shellguard_Game_State_GameLogic_State_Paused --> Shellguard_Game_State_GameLogic_State_Playing : PauseButtonPressed
Shellguard_Game_State_GameLogic_State_Playing --> Shellguard_Game_State_GameLogic_State_Paused : PauseButtonPressed

Shellguard_Game_State_GameLogic_State : OnIsPaused() → SetPauseMode
Shellguard_Game_State_GameLogic_State : OnSaving() → StartSaving

[*] --> Shellguard_Game_State_GameLogic_State_Playing
@enduml